// WebRTC configuration helper

// Free public Google STUN servers for NAT traversal
export const rtcConfig = {
  iceServers: [
    {
      urls: [
        'stun:stun.l.google.com:19302',
        'stun:stun1.l.google.com:19302',
        'stun:stun2.l.google.com:19302',
        'stun:stun3.l.google.com:19302',
        'stun:stun4.l.google.com:19302',
      ],
    },
  ],
};

/**
 * Creates a new RTCPeerConnection for a remote peer.
 * @param {string} remoteSocketId - Socket ID of the remote peer
 * @param {MediaStream} localStream - Local audio/video stream
 * @param {Function} onIceCandidate - Callback for sending ICE candidates
 * @param {Function} onTrack - Callback when remote video/audio track is received
 * @returns {RTCPeerConnection}
 */
export function createPeerConnection(
  remoteSocketId,
  localStream,
  onIceCandidate,
  onTrack
) {
  const pc = new RTCPeerConnection(rtcConfig);

  // Add all local tracks to the connection
  if (localStream) {
    localStream.getTracks().forEach((track) => {
      pc.addTrack(track, localStream);
    });
  }

  // Handle ICE candidates generated by the browser
  pc.onicecandidate = (event) => {
    if (event.candidate) {
      onIceCandidate(remoteSocketId, event.candidate);
    }
  };

  // Handle incoming remote media tracks
  pc.ontrack = (event) => {
    if (event.streams && event.streams[0]) {
      onTrack(remoteSocketId, event.streams[0]);
    }
  };

  // Log connection state changes for debugging
  pc.onconnectionstatechange = () => {
    console.log(`Connection state with peer ${remoteSocketId}: ${pc.connectionState}`);
  };

  return pc;
}
